{ config, pkgs, pkgs-unstable, ... }:

{
  environment.systemPackages = with pkgs; [
    neovim
    alacritty
    dmenu
    (lua.withPackages(ps: with ps; [ busted luafilesystem ]))
    git
    gnome-keyring
    cudatoolkit 
    nerdfonts
    networkmanagerapplet
    nitrogen
    pasystray
    picom
    maim
    xclip
    xdotool
    polkit_gnome
    pulseaudioFull
    mkdocs
    zip
    maven
    iosevka
    libngspice
    vscode
    rofi
    octaveFull
    home-manager
    hyperfine
    vim
    deno
    zellij
    android-studio
    curl
    zed-editor
    unrar
    lshw
    bun
    obs-studio
    unzip
    eww
    waybar
    libsForQt5.kdenlive
    brightnessctl
    neofetch
    zsh
    oh-my-zsh
    zsh-completions
    zsh-powerlevel10k
    zsh-syntax-highlighting
    libreoffice-qt
    hunspell
    hunspellDicts.uk_UA
    hunspellDicts.th_TH
    libngspice
    gwe
    go
    zsh-history-substring-search
    dunst
    cargo-tauri
    tree
    rustc
    nodejs_22
    pacman
    python311Packages.pip
    docker
    cargo
    gccgo14
    pkg-config
    gtk3
    davinci-resolve
    ngspice
    nvtopPackages.nvidia
    mongodb-compass
    postman
    geeqie
    viewnior
    vlc
    webkitgtk
    cairo
    rustup
    atk
    pkg-config
    discord
    python3
    openssl
    librsvg
    tmux
    kitty
    ranger
    spotifyd
    yazi
    appimagekit
    wezterm
    polybar
    grimblast
    ungoogled-chromium
    jdk
    react-native-debugger
    pfetch
    zip
    davinci-resolve
    eog
  ];
}
